@baseUrl = http://localhost:4400

### Register User
POST {{baseUrl}}/auth/register HTTP/1.1
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "password": "password123",
  "confirmPassword": "password123"
}

### Login User
POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "password123"
}

### Me
GET {{baseUrl}}/auth/me HTTP/1.1

### Sign Out User
POST {{baseUrl}}/auth/logout HTTP/1.1

